{{- if .Values.service.enabled }}
{{- $containerPort := include "workload.containerPort" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "workload.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.portName }}
      port: {{ .Values.service.port | default $containerPort }}
      targetPort: {{ $containerPort }}
      protocol: TCP
{{- end }}
