service:
  type: ClusterIP
  port: 8085

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: headlamp.home
      paths:
        - path: /
          type: Prefix

config:
  pluginsDir: ""
  oidc:
    secret:
      create: false
    callbackURL: http://headlamp.home/oidc-callback
    externalSecret:
      enabled: true
      # Created by terraform/authentik.tf as kubernetes_secret_v1.headlamp_oauth.
      name: headlamp-oauth-secret

clusterRoleBinding:
  create: true

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
