repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: pajikos
    url: http://pajikos.github.io/home-assistant-helm-chart/
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: longhorn
    url: https://charts.longhorn.io
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: prometheus-operator
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    values:
      - services/prometheus/values.yaml

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - services/grafana/values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - services/grafana/dashboards/metrics-dashboard-configmap.yaml
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - services/grafana/ingress.yaml

  - name: postgres
    namespace: postgres
    createNamespace: true
    chart: bitnami/postgresql
    values:
      - services/postgres/values.yaml
    hooks:
      # have to use bash to enable idempotent `helmfile sync` operations
      # without it, the command would fail on subsequent runs if the configmap already exists
      - events: ["presync"]
        showlogs: true
        command: bash
        args:
          - -c
          - |
            kubectl create namespace postgres --dry-run=client -o yaml | kubectl apply -f -
            kubectl create configmap postgres-bootstrap \
              --namespace=postgres \
              --from-file=services/postgres/bootstrap.sql \
              --dry-run=client -o yaml | kubectl apply -f -

  - name: home-assistant
    namespace: home-automation
    createNamespace: true
    chart: pajikos/home-assistant
    values:
      - services/home-assistant/values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - services/home-assistant/ingress.yaml

  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    values:
      - services/longhorn/values.yaml

  - name: traefik
    namespace: kube-system
    chart: traefik/traefik
    values:
      - services/traefik/values.yaml

  # this is a bitch to configure, it nukes my inter
  # - name: pihole
  #   namespace: pihole
  #   createNamespace: true
  #   chart: mojo2600/pihole
  #   values:
  #     - services/pihole/values.yaml

  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    values:
      - services/metallb/values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: bash
        args:
          - -c
          - |
            echo "Waiting for MetalLB webhook to be ready..."
            kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=controller -n metallb-system --timeout=60s
            kubectl apply -f services/metallb/ip-pool.yaml
# External resources to manually apply or automate separately:
# kubectl apply -f services/grafana/dashboards/metrics-dashboard-configmap.yaml
# kubectl apply -f services/metallb/config.yaml
# kubectl apply -f services/grafana/ingress.yaml
# kubectl apply -f services/home-assistant/ingress.yaml
