adminPassword: ENC[AES256_GCM,data:inoF72w=,iv:hL2KrQ/SWCmotc9/0Iq8KHo9uGzEWDUoPfO9yfWXZjs=,tag:aE/nk2iqfTsCvPeKyX0HmQ==,type:str]
sops:
  age:
    - recipient: age1k3876j8v8anfwv58cnunwj7wpdjluynqkzw5futvedfy5dft9qssnjqgyz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZEV6M3lUMExDQ1o3RUQy
        UTVqRExtSjFoRWxQaFpVU01PVGFZbFNiMFg4ClpjblhjQWhRRHo1RzdKWnJRZ2Vs
        TE5QWTFQUmI4Uk9LNjRyVlVRUFpkcVkKLS0tIGZHSGZOYWN4REExajc4MnlILzIz
        SzBVcThBMkkwSElhZEVmcUdsZGJzWTgK9dcr8aiQ7G1ViqFFrANP7BAuoxjrbfxS
        D2eFidPWmQ1m3HmXbgDvSJQD3PnFNJDeodddUomD6OpxCA1R4trtug==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1fjrj639zeu2368ldqetsn5gn5m25hfv9h229uqk33mff3as4t4yqrqwgj5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZTJhTWQ0eVVpYWozUkZD
        NUFVZGRuZzRESGJyL1pFMzA4REJDSjkzY0djCk5Yb2g5cG9SNUtiYVg1VmNiWThE
        S2xDMlJKTVZWbUpRMC9PZzV5RjdQY2MKLS0tIE9FT3hTWUhtTkVKNU8vRUJNWnk0
        N01NaUR6UDZpSWpqWG4wc1JjYlVRWnMK5Ek8WTT3TW3BkYCqjlTrP4K4skH+BRC/
        3pdzyvWWxB4sVt3G6Z6m7p1VQi/yGoaZieXDYBfZp0yNoi1EQxfiTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T00:34:52Z"
  mac: ENC[AES256_GCM,data:HyBfFMb3tewjGBh5Era8j2NaNBLAvYPaGczZn5+bIcQuCzw0p859j9/GQdMjBaQ0E09dpAYUfepgPjHmXh18aPZpwuNFFX6eosUKrC16reva3vy31H3Q3r2aEohmgpdPhljR8/wSyjGJfCHAwcGMvh2sTZSoUsK7aVwvcUI6uMY=,iv:lRGN+Fd6yxD4LZdDqhIwzYHQLaMjl40aXxLW5v9gE1w=,tag:qDTvl3/Zij4DADu5MRXbkA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
