--
-- PostgreSQL database dump
--

\restrict homelabSourceSchema


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: source; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA source;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: events_cs; Type: TABLE; Schema: source; Owner: -
--

CREATE TABLE source.events_cs (
    id bigint NOT NULL,
    source_event_id text NOT NULL,
    league text NOT NULL,
    event_name text NOT NULL,
    event_start timestamp with time zone NOT NULL,
    status text,
    team1 text,
    team2 text,
    tournament text,
    maps text,
    rating integer,
    source text NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    modified_at timestamp with time zone NOT NULL
);


--
-- Name: events_cs_id_seq; Type: SEQUENCE; Schema: source; Owner: -
--

ALTER TABLE source.events_cs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME source.events_cs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_google_calendar; Type: TABLE; Schema: source; Owner: -
--

CREATE TABLE source.events_google_calendar (
    id bigint NOT NULL,
    account_email text NOT NULL,
    calendar_id text NOT NULL,
    calendar_summary text,
    source_event_id text NOT NULL,
    source_instance_id text NOT NULL,
    event_name text NOT NULL,
    event_start timestamp with time zone NOT NULL,
    event_end timestamp with time zone,
    is_all_day boolean NOT NULL,
    status text NOT NULL,
    transparency text,
    visibility text,
    location text,
    html_link text,
    raw jsonb NOT NULL,
    source text NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    modified_at timestamp with time zone NOT NULL
);


--
-- Name: events_google_calendar_id_seq; Type: SEQUENCE; Schema: source; Owner: -
--

ALTER TABLE source.events_google_calendar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME source.events_google_calendar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_nba; Type: TABLE; Schema: source; Owner: -
--

CREATE TABLE source.events_nba (
    id bigint NOT NULL,
    source_event_id text NOT NULL,
    league text NOT NULL,
    event_name text NOT NULL,
    event_start timestamp with time zone NOT NULL,
    status text,
    home_team text,
    away_team text,
    venue text,
    source text NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    modified_at timestamp with time zone NOT NULL
);


--
-- Name: events_nba_id_seq; Type: SEQUENCE; Schema: source; Owner: -
--

ALTER TABLE source.events_nba ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME source.events_nba_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_ufc; Type: TABLE; Schema: source; Owner: -
--

CREATE TABLE source.events_ufc (
    id bigint NOT NULL,
    source_event_id text NOT NULL,
    league text NOT NULL,
    event_name text NOT NULL,
    event_start timestamp with time zone NOT NULL,
    location text,
    source_url text,
    source text NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    modified_at timestamp with time zone NOT NULL
);


--
-- Name: events_ufc_fighters; Type: TABLE; Schema: source; Owner: -
--

CREATE TABLE source.events_ufc_fighters (
    id bigint NOT NULL,
    source_event_id text NOT NULL,
    fighter_id text NOT NULL,
    fighter_name text NOT NULL,
    bout_id text,
    corner text,
    outcome text,
    source text NOT NULL,
    created_at timestamp with time zone DEFAULT statement_timestamp() NOT NULL,
    modified_at timestamp with time zone NOT NULL
);


--
-- Name: events_ufc_fighters_id_seq; Type: SEQUENCE; Schema: source; Owner: -
--

ALTER TABLE source.events_ufc_fighters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME source.events_ufc_fighters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_ufc_id_seq; Type: SEQUENCE; Schema: source; Owner: -
--

ALTER TABLE source.events_ufc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME source.events_ufc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personal_reminders; Type: TABLE; Schema: source; Owner: -
--

CREATE TABLE source.personal_reminders (
    id bigint NOT NULL,
    reminder_type text NOT NULL,
    reminder_message text NOT NULL,
    reminder_start_date date NOT NULL,
    reminder_end_date date,
    is_completed boolean NOT NULL,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: personal_reminders_id_seq; Type: SEQUENCE; Schema: source; Owner: -
--

ALTER TABLE source.personal_reminders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME source.personal_reminders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_cs events_cs_pkey; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_cs
    ADD CONSTRAINT events_cs_pkey PRIMARY KEY (id);


--
-- Name: events_cs events_cs_source_event_id_key; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_cs
    ADD CONSTRAINT events_cs_source_event_id_key UNIQUE (source_event_id);


--
-- Name: events_google_calendar events_google_calendar_pkey; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_google_calendar
    ADD CONSTRAINT events_google_calendar_pkey PRIMARY KEY (id);


--
-- Name: events_nba events_nba_pkey; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_nba
    ADD CONSTRAINT events_nba_pkey PRIMARY KEY (id);


--
-- Name: events_nba events_nba_source_event_id_key; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_nba
    ADD CONSTRAINT events_nba_source_event_id_key UNIQUE (source_event_id);


--
-- Name: events_ufc_fighters events_ufc_fighters_pkey; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_ufc_fighters
    ADD CONSTRAINT events_ufc_fighters_pkey PRIMARY KEY (id);


--
-- Name: events_ufc events_ufc_pkey; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_ufc
    ADD CONSTRAINT events_ufc_pkey PRIMARY KEY (id);


--
-- Name: events_ufc events_ufc_source_event_id_key; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_ufc
    ADD CONSTRAINT events_ufc_source_event_id_key UNIQUE (source_event_id);


--
-- Name: personal_reminders personal_reminders_pkey; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.personal_reminders
    ADD CONSTRAINT personal_reminders_pkey PRIMARY KEY (id);


--
-- Name: events_google_calendar uniq_events_google_calendar_instance; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_google_calendar
    ADD CONSTRAINT uniq_events_google_calendar_instance UNIQUE (account_email, calendar_id, source_instance_id);


--
-- Name: events_ufc_fighters uniq_events_ufc_fighters_event_fighter; Type: CONSTRAINT; Schema: source; Owner: -
--

ALTER TABLE ONLY source.events_ufc_fighters
    ADD CONSTRAINT uniq_events_ufc_fighters_event_fighter UNIQUE (source_event_id, fighter_id);


--
-- Name: events_cs_source_event_id_474ed76e_like; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX events_cs_source_event_id_474ed76e_like ON source.events_cs USING btree (source_event_id text_pattern_ops);


--
-- Name: events_nba_source_event_id_b2fc85c0_like; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX events_nba_source_event_id_b2fc85c0_like ON source.events_nba USING btree (source_event_id text_pattern_ops);


--
-- Name: events_ufc_source_event_id_90e11892_like; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX events_ufc_source_event_id_90e11892_like ON source.events_ufc USING btree (source_event_id text_pattern_ops);


--
-- Name: idx_events_gcal_account_seen; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX idx_events_gcal_account_seen ON source.events_google_calendar USING btree (account_email, calendar_id, last_seen_at);


--
-- Name: idx_events_gcal_start_end; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX idx_events_gcal_start_end ON source.events_google_calendar USING btree (event_start, event_end);


--
-- Name: idx_events_gcal_status; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX idx_events_gcal_status ON source.events_google_calendar USING btree (status);


--
-- Name: idx_personal_reminders_active; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX idx_personal_reminders_active ON source.personal_reminders USING btree (is_completed, reminder_start_date, reminder_end_date);


--
-- Name: idx_personal_reminders_type; Type: INDEX; Schema: source; Owner: -
--

CREATE INDEX idx_personal_reminders_type ON source.personal_reminders USING btree (reminder_type);


--
-- PostgreSQL database dump complete
--

\unrestrict homelabSourceSchema
