apiVersion: batch/v1
kind: CronJob
metadata:
  name: utc-logger
  namespace: default
spec:
  schedule: "*/1 * * * *" # runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: utc-logger
              image: jyablonski/go-cron-test:latest
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 50m
                  memory: 64Mi
          restartPolicy: OnFailure
