from typing import Protocol

from models import JobRun, Runnable


class RunnerClient(Protocol):
    def list_jobs(self) -> list[dict[str, object]]: ...

    def list_runnables(self) -> list[Runnable]: ...

    def list_runs(self, *, namespace: str, cronjob_name: str) -> list[JobRun]: ...

    def run(self, *, namespace: str, cronjob_name: str) -> JobRun: ...

    def run_job(self, *, app: str, name: str) -> dict[str, object]: ...

    def list_job_runs(self, *, app: str, name: str) -> list[dict[str, object]]: ...
