image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: stable

# Storage for recordings
persistence:
  data:
    enabled: true
    storageClass: longhorn
    size: 500Gi # TODO: adjust later down the line
    accessMode: ReadWriteOnce

# Service to access Frigate UI
service:
  type: LoadBalancer
  port: 5000

# Resource limits (adjust based on Beelink capacity)
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi
