grafana:
  adminPassword: ENC[AES256_GCM,data:V/PoRLk=,iv:yzRUm2qEmIzX7Uz+nDeera1W3cy1FOPfq67OCeFNTrg=,tag:DJoDa0RZ3eK290lgXh+bqg==,type:str]
sops:
  age:
    - recipient: age1k3876j8v8anfwv58cnunwj7wpdjluynqkzw5futvedfy5dft9qssnjqgyz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUEpqa21tN1ZjdXdpdWpI
        d3E1VXNGRWlEcEtXTVU3Sk0vakRRcWk2b0JvClVPQ205bTN6dDVqQzA4bERKS3VP
        TVN4Z2puWTB2QTFPbnFTSUxlam1scEUKLS0tIFRIS3cvVGpOOStiblpRWE5mdEVi
        cjRXVlM4SXZDOUdTOHZWZzFiaENURk0KuGuZAefaAPORNdl8Lmz+uxkp1pLHdeGQ
        Z0Nwhgg8CM+jc8cF6T941n1yLKt215YxRs9LIOVvo0Sx/A1JTsyqFA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1fjrj639zeu2368ldqetsn5gn5m25hfv9h229uqk33mff3as4t4yqrqwgj5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTXhiNU9kZnVuU1F5amE5
        WENmOERMaWxIZ2FxN29VWHRldmZTbDdlT0dZCmYxOGxDcFZiMkx4NklYU1JPejBs
        d3JlM2NqSnB0WGZJWmJPQ2Y2Z1ZBVkUKLS0tIDQ2dld5Z0FyVXZmNVh0Qk14UFpv
        QkpNZjU2UE9ROHd0OFJ4YmhuY21TYVEKgM3vvDujt7fWCRakDWL04UixtFaOLeiy
        oucGKni+vLA3NjaFUygg5uRkVxcB9CBG1C2CH1+8C5puliHdC9GIXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T00:29:36Z"
  mac: ENC[AES256_GCM,data:XP1Nv2pX9Ss7gCZyGgD5YZE+IWF7ySCfVXQ0a8iteHrW/nCGayOwi2aS6pF+jFt36qMW1r1d/j+hL76oWIzRu1XkND7uUi83phFiYQsw8WyFqzFyZrV1P8XiaqgUtFi8xq2xJwMdei/BNkTCwlTxpfWv89VlVe9Xzhe/raWJm8o=,iv:WIZtK86NrlU0DWdgbRP6Ck8Nl9+ao5YnIkwDKBKgjIc=,tag:qVv8KFrd2b89q4vAZHyqfg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
