grafana:
  adminPassword: ENC[AES256_GCM,data:pb3vuD1HZ9ilZhPYiuWid2GwRmTWicdt9qDQ5waR0sGli5thB2O/u51YZGM=,iv:Drkg5ANJXazSwWcP2rqCrpl9RaKGL2ZW9JmFzIpm7CI=,tag:BGyfIjC8l9k7IccJr8QtEw==,type:str]
alertmanagerSlack:
  webhookUrl: ENC[AES256_GCM,data:c1OVkm4LD01ZpPXHY2tma/Mx6rUjjXjMQ0keJ9VlwvrIaH3MrDf5WvKGZMW0jg6F8k7B8BtY0IO5tSZwS6weBXvAEJNXjmhjYJ/UdeXOO6Mh,iv:Z/XKthiD2wAi2E9XhwBWtm4TvQayCZ4PspXTHQDvbtc=,tag:dWSnm3JOVx+El1MmII2MgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUEpqa21tN1ZjdXdpdWpI
        d3E1VXNGRWlEcEtXTVU3Sk0vakRRcWk2b0JvClVPQ205bTN6dDVqQzA4bERKS3VP
        TVN4Z2puWTB2QTFPbnFTSUxlam1scEUKLS0tIFRIS3cvVGpOOStiblpRWE5mdEVi
        cjRXVlM4SXZDOUdTOHZWZzFiaENURk0KuGuZAefaAPORNdl8Lmz+uxkp1pLHdeGQ
        Z0Nwhgg8CM+jc8cF6T941n1yLKt215YxRs9LIOVvo0Sx/A1JTsyqFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k3876j8v8anfwv58cnunwj7wpdjluynqkzw5futvedfy5dft9qssnjqgyz
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTXhiNU9kZnVuU1F5amE5
        WENmOERMaWxIZ2FxN29VWHRldmZTbDdlT0dZCmYxOGxDcFZiMkx4NklYU1JPejBs
        d3JlM2NqSnB0WGZJWmJPQ2Y2Z1ZBVkUKLS0tIDQ2dld5Z0FyVXZmNVh0Qk14UFpv
        QkpNZjU2UE9ROHd0OFJ4YmhuY21TYVEKgM3vvDujt7fWCRakDWL04UixtFaOLeiy
        oucGKni+vLA3NjaFUygg5uRkVxcB9CBG1C2CH1+8C5puliHdC9GIXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fjrj639zeu2368ldqetsn5gn5m25hfv9h229uqk33mff3as4t4yqrqwgj5
  lastmodified: "2026-09-27T18:57:45Z"
  mac: ENC[AES256_GCM,data:wWcJmfMhNuEClEh0PrduyZcv7su6+d6uIjKDzYgSlcrytaE89YjB1XjunB2unDzE0LWFEmbBCtVXURdbjDFudKSpaCHuTmMmmf0J24zNZWz9ipqPkfleWC7LNnxAGAYeRgTO90iwio7lc3s57CKTO7+d2AkSc6/E3HH3rY2Zqa4=,iv:haB8+eGx9uGLaXDpOGSg+cNpVGORGoMSf5/8bni0VEw=,tag:IXWJgHohjmkE6kBa6kLfwA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
