persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: longhorn

controller:
  type: StatefulSet

hostNetwork: false
hostPort:
  enabled: false

service:
  type: LoadBalancer
  port: 8123

ingress:
  enabled: false
  external: false

serviceMonitor:
  enabled: true
  scrapeInterval: 30s
  labels:
    release: prometheus

replicaCount: 1
