persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: longhorn

controller:
  type: StatefulSet

hostNetwork: false
hostPort:
  enabled: false

service:
  type: LoadBalancer
  port: 8123

ingress:
  enabled: false
  external: false

serviceMonitor:
  enabled: true
  scrapeInterval: 30s
  labels:
    release: prometheus

# TODO: leave at 1 even in HA, home assistant is stateful because the local devices
# can only connect to 1 instance. the HA lives in longhorn storing the data w/ multiple
# replicas incase of failure.
replicaCount: 1
