defaultSettings:
  # have to be strings as of oct 2025, idfk bruh
  defaultReplicaCount: "1"
  storageMinimalAvailablePercentage: "10"

# TODO: change this to 3 for HA in prod setup
persistence:
  defaultClassReplicaCount: 1

service:
  ui:
    type: NodePort
    nodePort: 30085
