defaultSettings:
  # have to be strings as of oct 2025, idfk bruh
  defaultReplicaCount: "1"
  storageMinimalAvailablePercentage: "10"
  managerUrl: http://longhorn-backend:9500

  # TODO: change these for prod setup w/ 3 beelinks
  # storageMinimalAvailablePercentage: 20  # Stop scheduling if <20% free
  # storageOverProvisioningPercentage: 100
  # defaultReplicaCount: 3  # Highly available
  # guaranteedEngineManagerCPU: 12  # Percentage
  # guaranteedReplicaManagerCPU: 12

# TODO: change this to 3 for HA in prod setup
persistence:
  defaultClassReplicaCount: 1

service:
  ui:
    type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.home
  path: /
  pathType: Prefix
