import pytest
from dagster import materialize

from dagster_project.assets.exports.reminders import reminders_summary_export
from dagster_project.assets.ingestion.reminders import (
    reminders_raw,
    reminders_raw_non_negative,
)
from dagster_project.assets.transformations.reminders import reminders_daily

pytestmark = pytest.mark.integration


def test_reminders_pipeline_materializes(postgres_resource):
    _seed_reminders(postgres_resource, count=5)

    result = materialize(
        [reminders_raw, reminders_daily, reminders_summary_export],
        resources={"postgres": postgres_resource},
    )

    assert result.success
    assert result.output_for_node("reminders_raw") == 5
    assert result.output_for_node("reminders_daily") == {"reminder_count": 5}
    assert (
        postgres_resource.fetch_value(
            "SELECT reminder_count FROM source.reminders_summary"
        )
        == 5
    )


def test_reminders_check_passes(postgres_resource):
    _seed_reminders(postgres_resource, count=3)
    result = materialize(
        [reminders_raw, reminders_raw_non_negative],
        resources={"postgres": postgres_resource},
    )
    assert result.success
    check_evals = result.get_asset_check_evaluations()
    assert check_evals and all(c.passed for c in check_evals)


def _seed_reminders(postgres_resource, count: int) -> None:
    postgres_resource.execute(
        """
        CREATE TABLE source.reminders (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at timestamptz NOT NULL
        )
        """
    )
    for _idx in range(count):
        postgres_resource.execute(
            "INSERT INTO source.reminders (created_at) VALUES (now())"
        )
