# Generated by Django 6.0.4 on 2026-04-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_source_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_type", models.TextField()),
                ("reminder_message", models.TextField()),
                ("reminder_start_date", models.DateField()),
                ("reminder_end_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "personal_reminders",
                "indexes": [
                    models.Index(
                        fields=[
                            "is_completed",
                            "reminder_start_date",
                            "reminder_end_date",
                        ],
                        name="idx_personal_reminders_active",
                    ),
                    models.Index(
                        fields=["reminder_type"], name="idx_personal_reminders_type"
                    ),
                ],
            },
        ),
    ]
