# Generated by Django 6.0.4 on 2026-06-21 02:24

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_feature_flags_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventsCs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_event_id", models.TextField(unique=True)),
                ("league", models.TextField()),
                ("event_name", models.TextField()),
                ("event_start", models.DateTimeField()),
                ("status", models.TextField(blank=True, null=True)),
                ("team1", models.TextField(blank=True, null=True)),
                ("team2", models.TextField(blank=True, null=True)),
                ("tournament", models.TextField(blank=True, null=True)),
                ("maps", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("source", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("modified_at", models.DateTimeField()),
            ],
            options={
                "db_table": "events_cs",
            },
        ),
        migrations.CreateModel(
            name="EventsNba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_event_id", models.TextField(unique=True)),
                ("league", models.TextField()),
                ("event_name", models.TextField()),
                ("event_start", models.DateTimeField()),
                ("status", models.TextField(blank=True, null=True)),
                ("home_team", models.TextField(blank=True, null=True)),
                ("away_team", models.TextField(blank=True, null=True)),
                ("venue", models.TextField(blank=True, null=True)),
                ("source", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("modified_at", models.DateTimeField()),
            ],
            options={
                "db_table": "events_nba",
            },
        ),
        migrations.CreateModel(
            name="EventsUfc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_event_id", models.TextField(unique=True)),
                ("league", models.TextField()),
                ("event_name", models.TextField()),
                ("event_start", models.DateTimeField()),
                ("location", models.TextField(blank=True, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                ("source", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("modified_at", models.DateTimeField()),
            ],
            options={
                "db_table": "events_ufc",
            },
        ),
        migrations.CreateModel(
            name="EventsUfcFighter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_event_id", models.TextField()),
                ("fighter_id", models.TextField()),
                ("fighter_name", models.TextField()),
                ("bout_id", models.TextField(blank=True, null=True)),
                ("corner", models.TextField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("source", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("modified_at", models.DateTimeField()),
            ],
            options={
                "db_table": "events_ufc_fighters",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_event_id", "fighter_id"),
                        name="uniq_events_ufc_fighters_event_fighter",
                    )
                ],
            },
        ),
    ]
