# Generated by Django 6.0.4 on 2026-07-07 23:21

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_event_landing_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventsGoogleCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_email", models.TextField()),
                ("calendar_id", models.TextField()),
                ("calendar_summary", models.TextField(blank=True, null=True)),
                ("source_event_id", models.TextField()),
                ("source_instance_id", models.TextField()),
                ("event_name", models.TextField()),
                ("event_start", models.DateTimeField()),
                ("event_end", models.DateTimeField(blank=True, null=True)),
                ("is_all_day", models.BooleanField(default=False)),
                ("status", models.TextField()),
                ("transparency", models.TextField(blank=True, null=True)),
                ("visibility", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("html_link", models.TextField(blank=True, null=True)),
                ("raw", models.JSONField(default=dict)),
                ("source", models.TextField(default="google_calendar")),
                ("last_seen_at", models.DateTimeField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("modified_at", models.DateTimeField()),
            ],
            options={
                "db_table": "events_google_calendar",
                "indexes": [
                    models.Index(
                        fields=["event_start", "event_end"],
                        name="idx_events_gcal_start_end",
                    ),
                    models.Index(
                        fields=["account_email", "calendar_id", "last_seen_at"],
                        name="idx_events_gcal_account_seen",
                    ),
                    models.Index(fields=["status"], name="idx_events_gcal_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_email", "calendar_id", "source_instance_id"),
                        name="uniq_events_google_calendar_instance",
                    )
                ],
            },
        ),
    ]
