# Generated by Django 6.0.4 on 2026-08-29 19:14

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_eventsgooglecalendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="RssFeedEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_url", models.TextField()),
                ("entry_guid", models.TextField()),
                (
                    "posted_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "rss_feed_entries",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed_url", "entry_guid"),
                        name="uniq_rss_feed_entries_feed_guid",
                    )
                ],
            },
        ),
    ]
