ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - pihole.com
  paths:
    - /

persistentVolumeClaim:
  enabled: true
  storageClass: local-path

adminPassword: pihole

# Try these alternative service configurations
service:
  type: LoadBalancer

# Or try this format:
serviceWeb:
  type: ClusterIP

serviceDns:
  type: LoadBalancer

dnsmasq:
  customDnsEntries:
    - address=/homelab.com/192.168.76.132
    - address=/grafana.com/192.168.76.132
    - address=/prometheus.com/192.168.76.132
    - address=/pihole.com/192.168.76.132